/* ============================================================
   SYYTTÄJÄN TYÖPÖYTÄ — data.js
   Shared case data across all views.
   ============================================================ */

var CASES = [
  {
    id: 'R242847',
    diaarinumero: 'R 24/2847',
    kuvaus: 'Petos ja väärennys (Virtanen ym.)',
    status: 'syyteharkinnassa',
    statusLabel: 'Syyteharkinnassa',
    tuomioistuin: 'Helsingin KO',
    saapunut: '3.4.2024',
    maaraaika: '15.7.2025',
    maараikaUrgent: true,
    esitutkinta: '7100/R/3421/24',
    valmiusaste: 68,
    tags: ['Törkeä petos', 'Väärennys'],

    vastaajat: [
      { nimi: 'Virtanen, Markku Aleksi',  hetu: '150380-1234', ika: '45 v', syytekohdat: [1, 2] },
      { nimi: 'Korhonen, Sirpa Tuulikki', hetu: '220685-5678', ika: '40 v', syytekohdat: [1] },
      { nimi: 'Nieminen, Aleksi Juhani',  hetu: '120708A5555', ika: '16 v', syytekohdat: [2, 3] },
    ],
    asianomistajat: [
      { nimi: 'Järvinen, Paavo',  hetu: '260170-2222', ika: '55 v' },
      { nimi: 'Heikkinen, Leena', hetu: '150882-3333', ika: '42 v' },
      { nimi: 'Leinonen, Mats',   hetu: '010390-4444', ika: '35 v' },
    ],
    todistajat: [
      { nimi: 'Mäkinen, Esko',   rooli: 'Kirjanpitäjä' },
      { nimi: 'Saarinen, Jukka', rooli: 'Asiantuntijatodistaja' },
    ],

    charges: [
      {
        id: 'c1', num: 1, nimike: 'Törkeä petos', aika: '1.1.2023–31.12.2023', paikka: 'Helsinki',
        teonkuvaus: 'Virtanen on tekoaikana 1.1.2023–31.12.2023 Helsingissä, toimiessaan XYZ Capital Oy:n toimitusjohtajana, hankkiakseen itselleen oikeudetonta taloudellista hyötyä erehdyttänyt asianomistajia Järvistä, Heikkistä ja Leinosta esittämällä totuudenvastaisia tietoja yhtiön taloudellisesta tilanteesta ja sijoitustuotoista. Virtanen on väittänyt yhtiön hallinnoivan sijoitusvarallisuutta noin 12 miljoonan euron arvosta ja luvannut 15 prosentin vuotuisen tuoton, vaikka todellisuudessa sijoituksia ei ole tehty ja varallisuus on käytetty Virtasen henkilökohtaisiin menoihin ja aiempien sijoittajien maksuihin.\n\nPetollisilla vakuutuksillaan Virtanen on saanut asianomistajat luovuttamaan varallisuuttaan yhtiölle yhteensä 850 000 euron arvosta. Teko on tehty erityisen suunnitelmallisesti käyttämällä valehenkilöllisyyksiä ja väärennettyä asiakirja-aineistoa ja petos on kohdistunut useisiin asianomistajiin sekä kokonaisuutena arvioiden erityisen arvokkaaseen omaisuuteen.',
        riidattomat: 'Virtanen on myöntänyt toimineensa XYZ Capital Oy:n toimitusjohtajana tekoaikana. Virtanen on myöntänyt vastaanottaneensa asianomistajilta yhteensä 850 000 euroa. Virtanen ei ole kiistänyt, ettei sijoitustoimintaa ole harjoitettu esitetyssä laajuudessa.',
        kirjallinenTodistelu: [
          { teksti: 'XYZ Capital Oy:n kirjanpitodokumentit 1.1.2023–31.12.2023', teema: 'Sijoitustoimintaa ei harjoitettu väitetyssä laajuudessa' },
          { teksti: 'Sähköpostikirjeenvaihto Virtasen ja asianomistajien välillä 15.1.–18.3.2023', teema: 'Asianomistajia erehdytettiin petollisilla sijoitusvakuutuksilla' },
          { teksti: 'XYZ Capital Oy:n sijoitusesite "Growth Fund 2024" (väärennetty)', teema: 'Asianomistajille esitetyt tiedot olivat totuudenvastaisia' },
          { teksti: 'Pankkitiliotteet, tili FI12 3456 7890 (Virtanen, tammi–joulukuu 2023)', teema: 'Virtanen vastaanotti 850 000 euroa asianomistajilta' },
          { teksti: 'Kaupparekisteriote XYZ Capital Oy, 14.1.2024', teema: 'Virtanen toimi yhtiön toimitusjohtajana ja käytti siinä määräysvaltaa' },
        ],
        henkilotodistelu: [
          { teksti: 'Asianomistaja Paavo Järvinen', teema: 'Sai petolliset sijoituslupaukset ja luovutti varoja yhtiölle' },
          { teksti: 'Asianomistaja Leena Heikkinen', teema: 'Sai petolliset sijoituslupaukset ja luovutti varoja yhtiölle' },
          { teksti: 'Asianomistaja Mats Leinonen', teema: 'Sai petolliset sijoituslupaukset ja luovutti varoja yhtiölle' },
          { teksti: 'Asiantuntijatodistaja Esko Mäkinen, tilintarkastaja', teema: 'Sijoitustoiminnan puuttuminen ja varojen ohjautuminen' },
        ],
      },
      {
        id: 'c2', num: 2, nimike: 'Väärennys', aika: '15.3.2023', paikka: 'Helsinki',
        teonkuvaus: 'Virtanen ja Nieminen ovat yhdessä 15.3.2023 Helsingissä väärentäneet XYZ Capital Oy:n sijoitusesitteen "Growth Fund 2024" lisäämällä siihen totuudenvastaisia tietoja yhtiön hallinnoiman varallisuuden määrästä ja sijoitustoiminnan tuloksista. Nieminen on teknisesti toteuttanut väärentämisen muokkaamalla alkuperäistä asiakirjaa Virtasen ohjeiden mukaisesti. Väärennettyä asiakirjaa on käytetty petollisessa menettelyssä asianomistajien erehdyttämiseen.',
        riidattomat: 'Virtanen ja Nieminen ovat myöntäneet muokanneensa sijoitusesitettä. Asiakirja on tunnistettu väärennetyksi asiantuntijatutkimuksessa.',
        kirjallinenTodistelu: [
          { teksti: 'Alkuperäinen sijoitusesite "Growth Fund 2024" (aito versio)', teema: 'Väärennetyn version poikkeamat ovat näkyvissä vertailussa' },
          { teksti: 'Väärennetty sijoitusesite "Growth Fund 2024"', teema: 'Asiakirja sisältää totuudenvastaisia tietoja varallisuuden määrästä ja tuotoista' },
          { teksti: 'Digitaalinen forensiikkaraportti, Forensics Finland Oy 22.4.2024', teema: 'Nieminen suoritti muokkauksen Virtasen ohjauksessa' },
        ],
        henkilotodistelu: [
          { teksti: 'Asiantuntijatodistaja Jukka Saarinen, digitaalinen forensiikka', teema: 'Asiakirjan muokkaushistoria, ajankohta ja tekijä ovat selvitettävissä' },
        ],
      },
      {
        id: 'c3', num: 3, nimike: 'Laiton uhkaus', aika: '4.11.2023', paikka: 'Espoo',
        teonkuvaus: 'Nieminen on 4.11.2023 Espoossa uhannut asianomistaja Laine Tuomasta aiheuttaa tälle vakavaa vahinkoa, jos tämä ilmoittaa sijoituspetoksesta viranomaisille.',
        riidattomat: '',
        kirjallinenTodistelu: [],
        henkilotodistelu: [],
      },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Virtanen, Markku Aleksi',  hetu: '150380-1234 · 45 v' },
      { id: 'v1b', charge: 'c1', vastaaja: 'Korhonen, Sirpa Tuulikki', hetu: '220685-5678 · 40 v' },
      { id: 'v2a', charge: 'c2', vastaaja: 'Virtanen, Markku Aleksi',  hetu: '150380-1234 · 45 v' },
      { id: 'v2b', charge: 'c2', vastaaja: 'Nieminen, Aleksi Juhani',  hetu: '120708A5555 · 16 v' },
      { id: 'v3a', charge: 'c3', vastaaja: 'Nieminen, Aleksi Juhani',  hetu: '120708A5555 · 16 v' },
    ],

    huomiot: 3,
    huomiotItems: [
      { id: 'h1', teksti: 'Haastehakemus toimittamatta käräjäoikeuteen – tarkista toimitusmääräaika' },
      { id: 'h2', teksti: 'Korhosen puolustusasianajaja vaihtunut – päivitä yhteystiedot ja varmista tiedoksianto' },
      { id: 'h3', teksti: 'Korvausvaatimusten loppusumma (850 000 €) tarkistamatta ennen haastehakemuksen allekirjoitusta' },
    ],

    shBuckets: [
      { id: 'b1', type: 'hh', label: 'Haastehakemus 1' },
    ],
    shAssign: { v1a: 'b1', v1b: 'b1', v2a: 'b1', v2b: 'b1', v3a: 'b1' },

    yksityisoikeudellisetVaatimukset: [
      { otsikko: 'Korvausvaatimus – Järvinen', teksti: 'Asianomistaja Paavo Järvinen vaatii vastaaja Markku Aleksi Virtaselta vahingonkorvauksena <strong>200 000 euroa</strong> korkolain 4 §:n 1 momentin mukaisine korkoineen 15.1.2024 lukien.\n\nVaatimus perustuu rikoslain 36 luvun 2 §:n nojalla tehdyn törkeän petoksen aiheuttamaan taloudelliseen vahinkoon.' },
      { otsikko: 'Korvausvaatimus – Heikkinen', teksti: 'Asianomistaja Leena Heikkinen vaatii vastaaja Markku Aleksi Virtaselta vahingonkorvauksena <strong>350 000 euroa</strong> korkolain 4 §:n 1 momentin mukaisine korkoineen 22.1.2024 lukien.' },
      { otsikko: 'Korvausvaatimus – Leinonen', teksti: 'Asianomistaja Mats Leinonen vaatii vastaaja Markku Aleksi Virtaselta vahingonkorvauksena <strong>300 000 euroa</strong> korkolain 4 §:n 1 momentin mukaisine korkoineen 8.2.2024 lukien.' },
    ],

    lisatiedot: [
      { otsikko: 'Oikeuspaikkaa koskeva kannanotto', teksti: 'Asia kuuluu Helsingin käräjäoikeuden toimivaltaan, koska teot on tehty pääosin Helsingissä ja pääosa asianomistajista asuu Helsingissä.' },
      { otsikko: 'Seuraamuskannanotto', teksti: 'Syyttäjä vaatii Virtaselle ehdotonta vankeusrangaistusta rikoksen vakavuuden, suunnitelmallisuuden ja aiheutetun kokonaisvahingon (850 000 euroa) perusteella. Korhosen osalta syyttäjä vaatii ehdollista vankeusrangaistusta ottaen huomioon hänen avustajan roolensa ja nuorempi rikoshistoriansa.' },
      { otsikko: 'Muut lisätiedot', teksti: '', suljettu: true },
    ],
  },

  {
    id: 'R243891',
    diaarinumero: 'R 24/3891',
    kuvaus: 'Törkeä pahoinpitely (Heikkinen)',
    status: 'jaettu',
    statusLabel: 'Jaettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '12.6.2025',
    maaraaika: '28.7.2025',
    maараikaUrgent: false,
    esitutkinta: '7100/R/4521/25',
    valmiusaste: 0,
    tags: ['Törkeä pahoinpitely', 'Laiton uhkaus'],

    vastaajat: [
      { nimi: 'Heikkinen, Jari Petteri', hetu: '880412-3456', ika: '37 v', syytekohdat: [1, 2] },
    ],
    asianomistajat: [
      { nimi: 'Laine, Tuomas', hetu: '910305-7890', ika: '34 v' },
    ],
    todistajat: [
      { nimi: 'Mäkinen, Reetta', rooli: 'Silminnäkijä' },
    ],

    charges: [
      { id: 'c1', num: 1, nimike: 'Törkeä pahoinpitely', aika: '14.5.2025', paikka: 'Helsinki' },
      { id: 'c2', num: 2, nimike: 'Laiton uhkaus',       aika: '14.5.2025', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Heikkinen, Jari Petteri', hetu: '880412-3456 · 37 v' },
      { id: 'v2a', charge: 'c2', vastaaja: 'Heikkinen, Jari Petteri', hetu: '880412-3456 · 37 v' },
    ],

    huomiot: 0,

    shBuckets: [],
    shAssign:  {},
  },

  {
    id: 'R241019',
    diaarinumero: 'R 24/1019',
    kuvaus: 'Kavallus (Saarinen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '8.5.2024',
    maaraaika: '4.8.2025',
    maараikaUrgent: false,
    esitutkinta: '7100/R/2918/24',
    valmiusaste: 15,
    tags: ['Kavallus'],
    vastaajat: [
      { nimi: 'Saarinen, Kimmo Juhani', hetu: '770614-9012', ika: '48 v', syytekohdat: [1] },
    ],
    asianomistajat: [],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Kavallus', aika: '1.6.2022–30.9.2023', paikka: 'Vantaa' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Saarinen, Kimmo Juhani', hetu: '770614-9012 · 48 v' },
    ],
    huomiot: 1,
    huomiotItems: [
      { id: 'h1', teksti: 'Kirjanpitotarkastus kesken – esitutkinta odottaa lisätuloksia ennen syyteharkintaa' },
    ],

    shBuckets: [],
    shAssign:  {},
  },

  {
    id: 'R241102',
    diaarinumero: 'R 24/1102',
    kuvaus: 'Huumausainerikos (Nieminen, Korhonen)',
    status: 'odottaa',
    statusLabel: 'Odottaa',
    tuomioistuin: 'Helsingin KO',
    saapunut: '15.3.2024',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1847/24',
    valmiusaste: 0,
    tags: ['Huumausainerikos'],
    vastaajat: [
      { nimi: 'Nieminen, Aleksi Juhani',  hetu: '120708A5555', ika: '16 v', syytekohdat: [1] },
      { nimi: 'Korhonen, Sirpa Tuulikki', hetu: '220685-5678', ika: '40 v', syytekohdat: [1] },
    ],
    asianomistajat: [],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Huumausainerikos', aika: '2023–2024', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Nieminen, Aleksi Juhani',  hetu: '120708A5555 · 16 v' },
      { id: 'v1b', charge: 'c1', vastaaja: 'Korhonen, Sirpa Tuulikki', hetu: '220685-5678 · 40 v' },
    ],
    huomiot: 2,
    huomiotItems: [
      { id: 'h1', teksti: 'Nieminen on alaikäinen (16 v) – varmista nuorisorikosprosessin erityisvaatimukset' },
      { id: 'h2', teksti: 'Esitutkintapöytäkirja toimittamatta – pyydä poliisilta viipymättä' },
    ],

    shBuckets: [],
    shAssign:  {},
  },

  {
    id: 'R235241',
    diaarinumero: 'R 23/5241',
    kuvaus: 'Törkeä rattijuopumus (Mäkinen)',
    status: 'oikeudessa',
    statusLabel: 'Oikeudessa',
    tuomioistuin: 'Helsingin KO',
    saapunut: '2.2.2024',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/0314/24',
    valmiusaste: 100,
    tags: ['Törkeä rattijuopumus'],
    vastaajat: [
      { nimi: 'Mäkinen, Timo Antero', hetu: '650923-1234', ika: '60 v', syytekohdat: [1] },
    ],
    asianomistajat: [],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Törkeä rattijuopumus', aika: '3.1.2024', paikka: 'Espoo' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Mäkinen, Timo Antero', hetu: '650923-1234 · 60 v' },
    ],
    huomiot: 0,

    shBuckets: [{ id: 'b1', type: 'hh', label: 'Haastehakemus 1' }],
    shAssign:  { v1a: 'b1' },
  },
  {
    id: 'R242156',
    diaarinumero: 'R 24/2156',
    kuvaus: 'Varkaus ja maksuvälinepetos (Mäkinen)',
    status: 'syyteharkinnassa',
    statusLabel: 'Syyteharkinnassa',
    tuomioistuin: 'Helsingin KO',
    saapunut: '18.3.2024',
    maaraaika: '18.9.2024',
    maараikaUrgent: false,
    esitutkinta: '7100/R/2156/24',
    valmiusaste: 0,
    tags: ['Varkaus', 'Maksuvälinepetos'],
    vastaajat: [{ nimi: 'Mäkinen, Janne Petteri', hetu: '900514-2233', ika: '34 v', syytekohdat: [1,2] }],
    asianomistajat: [{ nimi: 'Prisma Oy', hetu: 'Y-1234567-8', ika: '' }],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Varkaus', aika: '12.3.2024', paikka: 'Helsinki' },
      { id: 'c2', num: 2, nimike: 'Maksuvälinepetos', aika: '12.3.2024', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Mäkinen, Janne Petteri', hetu: '900514-2233 · 34 v' },
      { id: 'v2a', charge: 'c2', vastaaja: 'Mäkinen, Janne Petteri', hetu: '900514-2233 · 34 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R242890',
    diaarinumero: 'R 24/2890',
    kuvaus: 'Pahoinpitely (Korhonen, Leinonen)',
    status: 'syyteharkinnassa',
    statusLabel: 'Syyteharkinnassa',
    tuomioistuin: 'Helsingin KO',
    saapunut: '5.4.2024',
    maaraaika: '5.10.2024',
    maараikaUrgent: false,
    esitutkinta: '7100/R/2890/24',
    valmiusaste: 0,
    tags: ['Pahoinpitely'],
    vastaajat: [
      { nimi: 'Korhonen, Mikael Juhani', hetu: '851122-4455', ika: '39 v', syytekohdat: [1] },
      { nimi: 'Leinonen, Tero Antero', hetu: '880330-6677', ika: '36 v', syytekohdat: [1] },
    ],
    asianomistajat: [{ nimi: 'Virtanen, Risto', hetu: '920811-3344', ika: '32 v' }],
    todistajat: [{ nimi: 'Heikkinen, Anna', rooli: 'Silminnäkijä' }],
    charges: [
      { id: 'c1', num: 1, nimike: 'Pahoinpitely', aika: '22.3.2024', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Korhonen, Mikael Juhani', hetu: '851122-4455 · 39 v' },
      { id: 'v1b', charge: 'c1', vastaaja: 'Leinonen, Tero Antero', hetu: '880330-6677 · 36 v' },
    ],
    huomiot: 1,
    huomiotItems: [{ id: 'h1', teksti: 'Asianomistajan lääkärinlausunto toimittamatta – tarvitaan ennen syytteen nostamista' }],
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251247',
    diaarinumero: 'R 25/1247',
    kuvaus: 'Petos (Aaltonen)',
    status: 'jaettu',
    statusLabel: 'Jaettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '3.3.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1247/25',
    valmiusaste: 0,
    tags: ['Petos'],
    vastaajat: [{ nimi: 'Aaltonen, Harri Kalevi', hetu: '750208-9900', ika: '50 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'Koskinen, Matti', hetu: '680417-1122', ika: '57 v' }],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Petos', aika: '10.1.2025', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Aaltonen, Harri Kalevi', hetu: '750208-9900 · 50 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R240891',
    diaarinumero: 'R 24/0891',
    kuvaus: 'Kirjanpitorikos (Lahtinen)',
    status: 'odottaa',
    statusLabel: 'Odottaa',
    tuomioistuin: 'Helsingin KO',
    saapunut: '14.2.2024',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/0891/24',
    valmiusaste: 0,
    tags: ['Kirjanpitorikos'],
    vastaajat: [{ nimi: 'Lahtinen, Pekka Olavi', hetu: '620903-5566', ika: '62 v', syytekohdat: [1] }],
    asianomistajat: [],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Kirjanpitorikos', aika: '2021–2023', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Lahtinen, Pekka Olavi', hetu: '620903-5566 · 62 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R241567',
    diaarinumero: 'R 24/1567',
    kuvaus: 'Laiton uhkaus (Tapio)',
    status: 'odottaa',
    statusLabel: 'Odottaa',
    tuomioistuin: 'Helsingin KO',
    saapunut: '1.3.2024',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1567/24',
    valmiusaste: 0,
    tags: ['Laiton uhkaus'],
    vastaajat: [{ nimi: 'Tapio, Ville Juhani', hetu: '930625-7788', ika: '31 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'Järvi, Kristiina', hetu: '870912-4433', ika: '37 v' }],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Laiton uhkaus', aika: '17.2.2024', paikka: 'Vantaa' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Tapio, Ville Juhani', hetu: '930625-7788 · 31 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251089',
    diaarinumero: 'R 25/1089',
    kuvaus: 'Velallisen petos (Savolainen)',
    status: 'odottaa',
    statusLabel: 'Odottaa',
    tuomioistuin: 'Helsingin KO',
    saapunut: '18.2.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1089/25',
    valmiusaste: 0,
    tags: ['Velallisen petos'],
    vastaajat: [{ nimi: 'Savolainen, Kaija Tuulikki', hetu: '710514-8899', ika: '54 v', syytekohdat: [1] }],
    asianomistajat: [],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Velallisen petos', aika: '2024', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Savolainen, Kaija Tuulikki', hetu: '710514-8899 · 54 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251301',
    diaarinumero: 'R 25/1301',
    kuvaus: 'Pahoinpitely (Lindqvist)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '7.3.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1301/25',
    valmiusaste: 0,
    tags: ['Pahoinpitely'],
    vastaajat: [{ nimi: 'Lindqvist, Marcus Erik', hetu: '960318-2211', ika: '29 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'Hakala, Niina', hetu: '980703-5544', ika: '27 v' }],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Pahoinpitely', aika: '1.3.2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Lindqvist, Marcus Erik', hetu: '960318-2211 · 29 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251388',
    diaarinumero: 'R 25/1388',
    kuvaus: 'Rattijuopumus (Heino)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '14.3.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1388/25',
    valmiusaste: 0,
    tags: ['Rattijuopumus'],
    vastaajat: [{ nimi: 'Heino, Kimmo Sakari', hetu: '820907-3344', ika: '43 v', syytekohdat: [1] }],
    asianomistajat: [],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Rattijuopumus', aika: '8.3.2025', paikka: 'Espoo' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Heino, Kimmo Sakari', hetu: '820907-3344 · 43 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251412',
    diaarinumero: 'R 25/1412',
    kuvaus: 'Kotirauhan rikkominen ja vahingonteko (Hämäläinen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '19.3.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1412/25',
    valmiusaste: 0,
    tags: ['Kotirauhan rikkominen', 'Vahingonteko'],
    vastaajat: [{ nimi: 'Hämäläinen, Petri Olavi', hetu: '870224-1122', ika: '38 v', syytekohdat: [1,2] }],
    asianomistajat: [{ nimi: 'Peltonen, Sirpa', hetu: '910614-6677', ika: '34 v' }],
    todistajat: [],
    charges: [
      { id: 'c1', num: 1, nimike: 'Kotirauhan rikkominen', aika: '10.3.2025', paikka: 'Helsinki' },
      { id: 'c2', num: 2, nimike: 'Vahingonteko', aika: '10.3.2025', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Hämäläinen, Petri Olavi', hetu: '870224-1122 · 38 v' },
      { id: 'v2a', charge: 'c2', vastaaja: 'Hämäläinen, Petri Olavi', hetu: '870224-1122 · 38 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251489',
    diaarinumero: 'R 25/1489',
    kuvaus: 'Varkaus (Rantanen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '25.3.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1489/25',
    valmiusaste: 0,
    tags: ['Varkaus'],
    vastaajat: [{ nimi: 'Rantanen, Sami Aleksi', hetu: '010502A1234', ika: '24 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'K-Market Kallio', hetu: 'Y-9876543-2', ika: '' }],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Varkaus', aika: '20.3.2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Rantanen, Sami Aleksi', hetu: '010502A1234 · 24 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251534',
    diaarinumero: 'R 25/1534',
    kuvaus: 'Seksuaalinen ahdistelu (Virtanen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '2.4.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1534/25',
    valmiusaste: 0,
    tags: ['Seksuaalinen ahdistelu'],
    vastaajat: [{ nimi: 'Virtanen, Jukka Matti', hetu: '780615-8844', ika: '47 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'Hakkarainen, Emilia', hetu: '020814A5566', ika: '23 v' }],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Seksuaalinen ahdistelu', aika: '25.3.2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Virtanen, Jukka Matti', hetu: '780615-8844 · 47 v' }],
    huomiot: 1,
    huomiotItems: [{ id: 'h1', teksti: 'Asianomistaja pyytänyt asiamiestä – tarkista edustajan yhteystiedot' }],
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251602',
    diaarinumero: 'R 25/1602',
    kuvaus: 'Törkeä rattijuopumus (Laitinen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '9.4.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1602/25',
    valmiusaste: 0,
    tags: ['Törkeä rattijuopumus'],
    vastaajat: [{ nimi: 'Laitinen, Olli Tapio', hetu: '661130-7722', ika: '59 v', syytekohdat: [1] }],
    asianomistajat: [],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Törkeä rattijuopumus', aika: '3.4.2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Laitinen, Olli Tapio', hetu: '661130-7722 · 59 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251677',
    diaarinumero: 'R 25/1677',
    kuvaus: 'Huumausaineen käyttörikos (Kärkkäinen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '14.4.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1677/25',
    valmiusaste: 0,
    tags: ['Huumausaineen käyttörikos'],
    vastaajat: [{ nimi: 'Kärkkäinen, Ville Tapani', hetu: '050606A3377', ika: '20 v', syytekohdat: [1] }],
    asianomistajat: [],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Huumausaineen käyttörikos', aika: '8.4.2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Kärkkäinen, Ville Tapani', hetu: '050606A3377 · 20 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251744',
    diaarinumero: 'R 25/1744',
    kuvaus: 'Petos (Turunen, Mäkinen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '22.4.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1744/25',
    valmiusaste: 0,
    tags: ['Petos'],
    vastaajat: [
      { nimi: 'Turunen, Hannu Sakari', hetu: '710822-5533', ika: '53 v', syytekohdat: [1] },
      { nimi: 'Mäkinen, Riikka Anneli', hetu: '741205-4422', ika: '51 v', syytekohdat: [1] },
    ],
    asianomistajat: [{ nimi: 'Leinonen, Paavo', hetu: '650301-9911', ika: '60 v' }],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Petos', aika: '2024', paikka: 'Helsinki' }],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Turunen, Hannu Sakari', hetu: '710822-5533 · 53 v' },
      { id: 'v1b', charge: 'c1', vastaaja: 'Mäkinen, Riikka Anneli', hetu: '741205-4422 · 51 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251811',
    diaarinumero: 'R 25/1811',
    kuvaus: 'Vahingonteko (Korhonen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '2.5.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1811/25',
    valmiusaste: 0,
    tags: ['Vahingonteko'],
    vastaajat: [{ nimi: 'Korhonen, Antti Ville', hetu: '991204A8844', ika: '26 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'Helsingin kaupunki / HKL', hetu: 'Y-2476981-4', ika: '' }],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Vahingonteko', aika: '28.4.2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Korhonen, Antti Ville', hetu: '991204A8844 · 26 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251889',
    diaarinumero: 'R 25/1889',
    kuvaus: 'Ryöstö (Salminen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '12.5.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1889/25',
    valmiusaste: 0,
    tags: ['Ryöstö'],
    vastaajat: [{ nimi: 'Salminen, Teemu Mikael', hetu: '030915A2233', ika: '22 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'Kauppinen, Irma', hetu: '580424-6611', ika: '67 v' }],
    todistajat: [{ nimi: 'Peltonen, Kari', rooli: 'Silminnäkijä' }],
    charges: [{ id: 'c1', num: 1, nimike: 'Ryöstö', aika: '7.5.2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Salminen, Teemu Mikael', hetu: '030915A2233 · 22 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R251956',
    diaarinumero: 'R 25/1956',
    kuvaus: 'Laiton uhkaus (Järvenpää)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '19.5.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/1956/25',
    valmiusaste: 0,
    tags: ['Laiton uhkaus'],
    vastaajat: [{ nimi: 'Järvenpää, Mika Juhani', hetu: '841019-4455', ika: '41 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'Niemi, Susanna', hetu: '891122-7788', ika: '36 v' }],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Laiton uhkaus', aika: '12.5.2025', paikka: 'Vantaa' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Järvenpää, Mika Juhani', hetu: '841019-4455 · 41 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R252034',
    diaarinumero: 'R 25/2034',
    kuvaus: 'Kulkuneuvon kuljettaminen oikeudetta (Pitkänen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '27.5.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/2034/25',
    valmiusaste: 0,
    tags: ['Kulkuneuvon kuljettaminen oikeudetta'],
    vastaajat: [{ nimi: 'Pitkänen, Jere Aleksi', hetu: '060818A9900', ika: '19 v', syytekohdat: [1] }],
    asianomistajat: [],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Kulkuneuvon kuljettaminen oikeudetta', aika: '22.5.2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Pitkänen, Jere Aleksi', hetu: '060818A9900 · 19 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R252109',
    diaarinumero: 'R 25/2109',
    kuvaus: 'Pahoinpitely ja uhkaus (Toivonen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '3.6.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/2109/25',
    valmiusaste: 0,
    tags: ['Pahoinpitely', 'Laiton uhkaus'],
    vastaajat: [{ nimi: 'Toivonen, Lassi Pekka', hetu: '790306-2266', ika: '46 v', syytekohdat: [1,2] }],
    asianomistajat: [{ nimi: 'Repo, Taina', hetu: '820509-8833', ika: '43 v' }],
    todistajat: [{ nimi: 'Koskela, Heikki', rooli: 'Naapuri' }],
    charges: [
      { id: 'c1', num: 1, nimike: 'Pahoinpitely', aika: '28.5.2025', paikka: 'Helsinki' },
      { id: 'c2', num: 2, nimike: 'Laiton uhkaus', aika: '28.5.2025', paikka: 'Helsinki' },
    ],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Toivonen, Lassi Pekka', hetu: '790306-2266 · 46 v' },
      { id: 'v2a', charge: 'c2', vastaaja: 'Toivonen, Lassi Pekka', hetu: '790306-2266 · 46 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R252188',
    diaarinumero: 'R 25/2188',
    kuvaus: 'Huumausainerikos (Matila)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '9.6.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/2188/25',
    valmiusaste: 0,
    tags: ['Huumausainerikos'],
    vastaajat: [
      { nimi: 'Matila, Riku Juhani', hetu: '900114-3355', ika: '35 v', syytekohdat: [1] },
      { nimi: 'Helin, Sonja Kaarina', hetu: '920803-7711', ika: '33 v', syytekohdat: [1] },
    ],
    asianomistajat: [],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Huumausainerikos', aika: '2024–2025', paikka: 'Helsinki' }],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Matila, Riku Juhani', hetu: '900114-3355 · 35 v' },
      { id: 'v1b', charge: 'c1', vastaaja: 'Helin, Sonja Kaarina', hetu: '920803-7711 · 33 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R252267',
    diaarinumero: 'R 25/2267',
    kuvaus: 'Petos (Väisänen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '14.6.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/2267/25',
    valmiusaste: 0,
    tags: ['Petos'],
    vastaajat: [{ nimi: 'Väisänen, Timo Kalevi', hetu: '680222-6644', ika: '57 v', syytekohdat: [1] }],
    asianomistajat: [{ nimi: 'Lehtonen, Kaarina', hetu: '700808-3322', ika: '56 v' }],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Petos', aika: '2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Väisänen, Timo Kalevi', hetu: '680222-6644 · 57 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R252344',
    diaarinumero: 'R 25/2344',
    kuvaus: 'Törkeä varkaus (Heikkinen, Ojala)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '20.6.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/2344/25',
    valmiusaste: 0,
    tags: ['Törkeä varkaus'],
    vastaajat: [
      { nimi: 'Heikkinen, Petteri Mikael', hetu: '910417-5566', ika: '34 v', syytekohdat: [1] },
      { nimi: 'Ojala, Risto Tapani', hetu: '890212-7788', ika: '36 v', syytekohdat: [1] },
    ],
    asianomistajat: [{ nimi: 'Nieminen, Annikki', hetu: '570315-2211', ika: '68 v' }],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Törkeä varkaus', aika: '15.6.2025', paikka: 'Helsinki' }],
    vaatimukset: [
      { id: 'v1a', charge: 'c1', vastaaja: 'Heikkinen, Petteri Mikael', hetu: '910417-5566 · 34 v' },
      { id: 'v1b', charge: 'c1', vastaaja: 'Ojala, Risto Tapani', hetu: '890212-7788 · 36 v' },
    ],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R252421',
    diaarinumero: 'R 25/2421',
    kuvaus: 'Rattijuopumus (Koistinen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '24.6.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/2421/25',
    valmiusaste: 0,
    tags: ['Rattijuopumus'],
    vastaajat: [{ nimi: 'Koistinen, Eero Juhani', hetu: '771109-9922', ika: '48 v', syytekohdat: [1] }],
    asianomistajat: [],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Rattijuopumus', aika: '20.6.2025', paikka: 'Espoo' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Koistinen, Eero Juhani', hetu: '771109-9922 · 48 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },

  {
    id: 'R252499',
    diaarinumero: 'R 25/2499',
    kuvaus: 'Maksuvälinepetos (Ahonen)',
    status: 'vastaanotettu',
    statusLabel: 'Vastaanotettu',
    tuomioistuin: 'Helsingin KO',
    saapunut: '26.6.2025',
    maaraaika: null,
    maараikaUrgent: false,
    esitutkinta: '7100/R/2499/25',
    valmiusaste: 0,
    tags: ['Maksuvälinepetos'],
    vastaajat: [{ nimi: 'Ahonen, Laura Kristiina', hetu: '000726A4477', ika: '25 v', syytekohdat: [1] }],
    asianomistajat: [],
    todistajat: [],
    charges: [{ id: 'c1', num: 1, nimike: 'Maksuvälinepetos', aika: '2025', paikka: 'Helsinki' }],
    vaatimukset: [{ id: 'v1a', charge: 'c1', vastaaja: 'Ahonen, Laura Kristiina', hetu: '000726A4477 · 25 v' }],
    huomiot: 0,
    shBuckets: [],
    shAssign: {},
  },
];

function getCaseById(id) {
  return CASES.find(function(c) { return c.id === id; }) || CASES[0];
}

function getCaseIdFromUrl() {
  var hash = window.location.hash.replace('#', '');
  return hash || CASES[0].id;
}
